# Import and export of data
The following notebook imports the raw data from the unstructured, original datasets (excel files) and converts the data into structured .csv-files for the analysis. No data transformation is done here, but the names of employees are filtered out.

## Package imports

In [1]:
import pandas as pd

## Dataset - Terminal data R25

In [17]:
# Import
df_alna_25 = pd.read_excel("../data/raw/Terminalrapportering R25_Alnabru (GAMMEL).xlsm",
                   sheet_name="Terminallogg R25", header=12, usecols="A:U,Z:AA")
df_alna_25.head()

c:\Users\krist\Documents\DOKUMENTER\Programmering\NMBU\masteroppgave26SixSigmaDataanalyse\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\krist\Documents\DOKUMENTER\Programmering\NMBU\masteroppgave26SixSigmaDataanalyse\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Merknad,Spor,Tognummer,Terminal,Avgangsdato,Uke,Dag,Lastefrist,Ferdig opplastet,Avvik - lasteforsinkelse,...,Planlagt klart fra terminal,Klart fra terminal,Avvik - terminalforsinkelse,Planlagt avgang,Faktisk avgang,Avvik - avgangsforsinkelse,Årsakskode - avgangsforsinkelse,Kommentar,Forsinkelsesminutter,LoggTogID
0,NaN,C32 Nord,5531.0,Alnabru,2024-12-30 00:00:00,53.0,Mandag,07:50,NaN,0.0,...,08:18:00,NaN,0.000000e+00,08:23:00,NaN,0.0,NaN,NaN,0.0,30-12-2024_5531
1,Lastefristkl. 19:30 dag før avgang.,C23,5301.0,Alnabru,2024-12-30 00:00:00,53.0,Mandag,19:30,NaN,0.0,...,08:46:00,08:46:00,7.993606e-14,08:51:00,09:05:00,-14.0,T16 - Kø skifting,NaN,-14.0,30-12-2024_5301
2,NaN,C32,5801.0,Alnabru,2024-12-30 00:00:00,53.0,Mandag,08:50,09:00:00,-10.0,...,09:26:00,09:20:00,6.000000e+00,09:31:00,09:32:00,-1.0,NaN,NaN,-1.0,30-12-2024_5801
3,PRI-TOG,C23,5731.0,Alnabru,2024-12-30 00:00:00,53.0,Mandag,08:50,09:30:00,-40.0,...,09:37:00,09:46:00,-9.000000e+00,09:42:00,09:52:00,-10.0,NaN,NaN,-10.0,30-12-2024_5731
4,NaN,C42,5507.0,Alnabru,2024-12-30 00:00:00,53.0,Mandag,11:40,11:40:00,0.0,...,12:18:00,12:00:00,1.800000e+01,12:23:00,12:16:00,7.0,NaN,NaN,7.0,30-12-2024_5507

In [ ]:
# Export to csv
df_alna_25.to_csv("../data/alnabrulogg_R25.csv", index=False, sep=";", encoding="utf-8-sig")

## Dataset - Terminal data R26

In [23]:
# Import
df_alna_26 = pd.read_excel("../data/raw/Terminalrapportering R26_Alnabru kopi.xlsm",
                   sheet_name="Terminallogg R26", header=12, usecols="A:U,Z:AA")
df_alna_26.head()

c:\Users\krist\Documents\DOKUMENTER\Programmering\NMBU\masteroppgave26SixSigmaDataanalyse\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\krist\Documents\DOKUMENTER\Programmering\NMBU\masteroppgave26SixSigmaDataanalyse\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Merknad,Spor,Tognummer,Terminal,Avgangsdato,Uke,Dag,Lastefrist,Ferdig opplastet,Avvik - lasteforsinkelse,...,Planlagt klart fra terminal,Klart fra terminal,Avvik - terminalforsinkelse,Planlagt avgang,Faktisk avgang,Avvik - avgangsforsinkelse,Årsakskode - avgangsforsinkelse,Kommentar,Forsinkelsesminutter,LoggTogID
0,Lastefristkl. 19:30 dag før avgang.,C45,5301.0,Alnabru,2026-01-01,1.0,Torsdag,19:30:00,NaN,0.0,...,08:46:00,NaN,0.0,08:51:00,NaN,0.0,NaN,NaN,0.0,01-01-2026_5301
1,NaN,C45,5801.0,Alnabru,2026-01-01,1.0,Torsdag,08:50:00,NaN,0.0,...,09:26:00,NaN,0.0,09:31:00,NaN,0.0,NaN,NaN,0.0,01-01-2026_5801
2,PRI-TOG,C42,5731.0,Alnabru,2026-01-01,1.0,Torsdag,08:50:00,NaN,0.0,...,09:37:00,NaN,0.0,09:42:00,NaN,0.0,NaN,NaN,0.0,01-01-2026_5731
3,NaN,C32,5507.0,Alnabru,2026-01-01,1.0,Torsdag,11:40:00,NaN,0.0,...,12:18:00,NaN,0.0,12:23:00,NaN,0.0,NaN,NaN,0.0,01-01-2026_5507
4,NaN,C42,45960.0,Alnabru,2026-01-01,1.0,Torsdag,14:00:00,NaN,0.0,...,15:37:00,NaN,0.0,15:42:00,NaN,0.0,NaN,NaN,0.0,01-01-2026_45960

In [24]:
# Export to csv
df_alna_26.to_csv("../data/alnabrulogg_R26.csv", index=False, sep=";", encoding="utf-8-sig")

## Dataset - TIOS

In [41]:
# Imports and initial column/row selection

df_tios = (pd.read_html("../data/raw/ExcelReport-6f2dcb04-d1bc-4d7e-b997-cbd3a93fe1b3.xls", match="Tognr", header=0, encoding="utf-8")[0]
      .drop(columns=["Unnamed: 3", "Unnamed: 4"]))
df_tios = df_tios[~df_tios["Dato"].str.startswith("Sum", na=False)]    # Remove the summary row at the bottom

df_tios.head()
df_tios.tail()

,Dato,Tognr,Stasjon,Innstilt,Forsinkelse,Årsak,HL-ID,HL-beskrivelse,Forårsakende,Kommentar
1865,24.09.2026,5811,Alnabru,Nei,00:21,82.0,NaN,NaN,NaN,NaN
1866,24.09.2026,81960,Alnabru,Nei,01:07,82.0,NaN,NaN,NaN,ikke klar før 0844
1867,25.09.2026,5301,Alnabru,Nei,00:45,82.0,NaN,NaN,NaN,NaN
1868,25.09.2026,5507,Alnabru,Nei,00:27,82.0,NaN,NaN,NaN,NaN
1869,25.09.2026,5801,Alnabru,Nei,00:37,82.0,NaN,NaN,NaN,NaN

In [43]:
# Export to csv
df_tios.to_csv("../data/tios_Alnabru_delays_R25_R26.csv", index=False, sep=";", encoding="utf-8-sig")

## Dataset - TIOS "Operating Train Route (OTR)" from Vy

In [48]:
# Import
df_tios_time = pd.read_csv("../data/raw/bronze_tp_operating_train_routes_ALB.csv", na_values=["null"],
                           usecols=lambda c: c not in ["line_id", "train_type", "train_kind"])   # helt tomme kolonner

df_tios_time.head()
df_tios_time.tail()

,train_id,train_date,source_country_code,active,cancelled,origin_stop_id,destination_stop_id,origin_stop_country,origin_time,train_company,...,scheduled_track_changes,train_kind_departure,train_kind_arrival,stop_id,stop_cancelled,arrival_delay,departure_delay,zx_timestamp_added,zx_timestamp_updated,zx_source_system
19947,85506,2025-08-01,NO,False,N,BRG,ALB,NO,2025-08-01T06:48:00.000Z,CN,...,"[{""change_time"":""2025-07-31T12:48:14.031+02:00...",NaN,Gt,ALB,N,-72.0,NaN,2025-08-06T02:49:53.282Z,2025-08-06T02:49:53.282Z,Operating Train Routes
19948,85805,2025-08-01,NO,True,N,ALB,MJD,NO,2025-08-01T11:30:00.000Z,CN,...,"[{""change_time"":""2025-07-31T17:30:16.488+02:00...",Gt,NaN,ALB,N,NaN,-5.0,2025-08-06T02:49:53.282Z,2025-08-06T02:49:53.282Z,Operating Train Routes
19949,85806,2025-08-01,NO,False,N,MJD,ALB,NO,2025-08-01T03:18:00.000Z,CN,...,"[{""change_time"":""2025-07-31T09:18:14.677+02:00...",NaN,Gt,ALB,N,-76.0,NaN,2025-08-06T02:49:53.282Z,2025-08-06T02:49:53.282Z,Operating Train Routes
19950,85811,2025-08-01,NO,False,N,ALB,MJD,NO,2025-08-01T16:30:00.000Z,CN,...,"[{""change_time"":""2025-07-31T22:30:13.329+02:00...",Gt,NaN,ALB,N,NaN,0.0,2025-08-06T02:49:53.282Z,2025-08-06T02:49:53.282Z,Operating Train Routes
19951,85814,2025-08-01,NO,False,N,MJD,ALB,NO,2025-08-01T01:26:00.000Z,CN,...,"[{""change_time"":""2025-07-31T07:26:15.375+02:00...",NaN,Gt,ALB,N,-8.0,NaN,2025-08-06T02:49:53.282Z,2025-08-06T02:49:53.282Z,Operating Train Routes

In [49]:
# Export to csv
df_tios_time.to_csv("../data/tios_Alnabru_allRegisteredDataOnTrains", index=False, sep=";", encoding="utf-8-sig")

## Dataset table - Terminalkoder mapping til TIOS årsakskoder

In [52]:
# Import – mapping mellom CargoNets terminalkoder og Bane NORs årsakskoder
df_kodemapping = pd.read_excel("../data/raw/Terminalrapportering R26_Alnabru kopi.xlsm", sheet_name="Årsakskodelister (IKKE REDIGER!", header=7, usecols="A:B,D:E", nrows=34)

df_kodemapping.head()
df_kodemapping.tail()

,Kode,Kort beskrivelse,Nedtrekks-tekst,Tilhørende YtelsesordningKode
29,T30,Øvrig toggang,T30 - Øvrig toggang,Kode 7 - Trafikkavvikling (Infrastrukturs andel)
30,T31,Mangelfull snørydding av spor,T31 - Mangelfull snørydding av spor,Kode 1 - Bane
31,T32,Mangelfull snørydding av lastegater/terminal,T32 - Mangelfull snørydding av lastegater/term...,Kode 1 - Bane
32,T33,Feil på løfteutstyr,T33 - Feil på løfteutstyr,Kode 84 - Stasjonsopphold
33,T34,"Annen feil, forklaring i kommentarfelt","T34 - Annen feil, forklaring i kommentarfelt",Kode 94 - Uønsket hendelse

In [53]:
# Export to csv
df_kodemapping.to_csv("../data/aarsakskoderMapping", index=False, sep=";", encoding="utf-8-sig")