# Analysis phase - analysis of terminal processes and how they affect train departure delays from Alnabru

## Data import and format verification

In [3]:
import pandas as pd
pd.set_option("mode.string_storage", "python")

df = pd.read_parquet(
    "../data/cleaned_data/combined_cleaned_terminal_dataset.parquet"
)


print("Rows:", len(df))
print("Columns:", len(df.columns))

display(df.head())

Rows: 5219
Columns: 35

,Merknad,Tognummer,Avgangsdato,Lastefrist,Ferdig opplastet,Frist lok,Lok ankommet,Planlagt klart fra terminal,Klart fra terminal,Planlagt avgangstid - terminal,...,train_id,train_date,cancelled,Planlagt avgangstid - OTR,Faktisk avgangstid - OTR,actual_arrival_time,estimated_arrival_time,just_passing_through,Forsinkelse - OTR,train_company
0,PRI-TOG,5731,2025-08-01,08:50:00,08:45:00,09:02:00,08:30:00,09:37:00,08:58:00,09:42:00,...,5731,2025-08-01,N,09:42:00,09:15:00,<NA>,<NA>,False,-27,CN
1,NaN,5507,2025-08-01,11:40:00,11:40:00,11:43:00,12:00:00,12:18:00,11:30:00,12:23:00,...,5507,2025-08-01,N,12:16:00,12:22:00,<NA>,<NA>,False,6,CN
2,PRI-TOG,41900,2025-08-01,19:35:00,19:30:00,19:46:00,20:00:00,20:21:00,20:00:00,20:26:00,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,NaN,5709,2025-08-01,20:20:00,20:20:00,20:32:00,20:10:00,21:07:00,20:30:00,21:12:00,...,5709,2025-08-01,N,21:12:00,21:04:00,<NA>,<NA>,False,-8,CN
4,LANGTOG,5515,2025-08-01,21:15:00,21:15:00,21:17:00,20:57:00,21:52:00,21:15:00,21:57:00,...,5515,2025-08-01,N,21:57:00,21:42:00,<NA>,<NA>,False,-15,CN

In [4]:
# Data type for every column
display(df.dtypes.to_frame("Data type"))

# More detailed structural overview
df.info()

                                       Data type
Merknad                                      str
Tognummer                                 string
Avgangsdato                       datetime64[us]
Lastefrist                                string
Ferdig opplastet                          string
Frist lok                                 string
Lok ankommet                              string
Planlagt klart fra terminal               string
Klart fra terminal                        string
Planlagt avgangstid - terminal            string
Faktisk avgangstid - terminal             string
Årsakskode - terminal                     string
Kommentar - terminal                         str
LoggTogID                                 string
Forsinkelse - terminal                     Int64
Mapped ytelsesordningkode                 string
Mapped ytelsesordningkode (tall)          string
Dato                              datetime64[us]
Tognr                                     string
Innstilt                                  string
Forsinkelse                                  str
Årsakskode - TIOS                         string
HL-beskrivelse - TIOS                     string
Kommentar - TIOS                          string
Forsinkelse - TIOS                         Int64
train_id                                  string
train_date                        datetime64[us]
cancelled                                 string
Planlagt avgangstid - OTR                 string
Faktisk avgangstid - OTR                  string
actual_arrival_time                       string
estimated_arrival_time                    string
just_passing_through                      string
Forsinkelse - OTR                          Int64
train_company                             string

<class 'pandas.DataFrame'>
RangeIndex: 5219 entries, 0 to 5218
Data columns (total 35 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Merknad                           2189 non-null   str
 1   Tognummer                         5219 non-null   string
 2   Avgangsdato                       5219 non-null   datetime64[us]
 3   Lastefrist                        5153 non-null   string
 4   Ferdig opplastet                  4640 non-null   string
 5   Frist lok                         5214 non-null   string
 6   Lok ankommet                      4560 non-null   string
 7   Planlagt klart fra terminal       5213 non-null   string
 8   Klart fra terminal                4620 non-null   string
 9   Planlagt avgangstid - terminal    5212 non-null   string
 10  Faktisk avgangstid - terminal     4797 non-null   string
 11  Årsakskode - terminal             1220 non-null   string
 12  Kommentar - terminal              684 non-null    str
 13  LoggTogID                         5219 non-null   string
 14  Forsinkelse - terminal            4793 non-null   Int64
 15  Mapped ytelsesordningkode         1151 non-null   string
 16  Mapped ytelsesordningkode (tall)  1151 non-null   string
 17  Dato                              1201 non-null   datetime64[us]
 18  Tognr                             1201 non-null   string
 19  Innstilt                          1201 non-null   string
 20  Forsinkelse                       1201 non-null   str
 21  Årsakskode - TIOS                 1201 non-null   string
 22  HL-beskrivelse - TIOS             214 non-null    string
 23  Kommentar - TIOS                  859 non-null    string
 24  Forsinkelse - TIOS                1201 non-null   Int64
 25  train_id                          4401 non-null   string
 26  train_date                        4401 non-null   datetime64[us]
 27  cancelled                         4401 non-null   string
 28  Planlagt avgangstid - OTR         4401 non-null   string
 29  Faktisk avgangstid - OTR          4401 non-null   string
 30  actual_arrival_time               27 non-null     string
 31  estimated_arrival_time            1 non-null      string
 32  just_passing_through              4401 non-null   string
 33  Forsinkelse - OTR                 4401 non-null   Int64
 34  train_company                     4401 non-null   string
dtypes: Int64(3), datetime64[us](3), str(3), string(26)
memory usage: 1.4 MB

## Actual analysis